In [1]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('/Users/TerryONeill/Terry_git/Capstone/GABBERT/wide_receivers/catcherr.csv')
df.head()

,Unnamed: 0,name,season,age,draft_pos,team,weight,bmi,games,rush_atts,...,pct_team_tgts,pct_team_receptions,pct_of_team_passyards,pct_team_touchdowns,years_in_league,dropK,yacK,base,td_points,compilation
0,0,David Boston,1999.0,21.0,1-8,ARI,240.0,30.8,16.0,5.0,...,0.145161,0.139373,0.168748,0.181818,0.0,1.609438,31.985201,0.074346,0.159658,8.552186
1,1,Frank Sanders,1999.0,26.0,2-47,ARI,215.0,27.6,16.0,0.0,...,0.274194,0.275261,0.340350,0.090909,0.0,2.708050,70.315514,0.369168,0.039915,37.196235
2,2,Rob Moore,1999.0,31.0,1-1,ARI,203.0,25.4,14.0,0.0,...,0.172043,0.128920,0.221548,0.454545,0.0,1.386294,17.753623,0.128205,0.997865,19.805583
3,3,Mac Cody,1999.0,27.0,UDFA,ARI,182.0,25.4,13.0,0.0,...,0.019713,0.020906,0.021406,0.090909,0.0,0.000000,7.350000,0.002884,0.039915,0.567829
4,4,Frank Sanders,2000.0,27.0,2-47,ARI,215.0,27.6,16.0,0.0,...,0.209386,0.170886,0.230462,0.375000,1.0,2.484907,37.234980,0.235628,0.987886,30.478033

In [3]:
## dropping index column that gets created

df.drop('Unnamed: 0', axis = 1, inplace = True)

In [4]:
df.columns

Index([u'name', u'season', u'age', u'draft_pos', u'team', u'weight', u'bmi',
       u'games', u'rush_atts', u'rush_yds', u'rush_y/a', u'rush_tds',
       u'rush_ypg', u'targets', u'receptions', u'rec_yards',
       u'yards/reception', u'rec_tds', u'rec_ypg', u'ctch_pct', u'y/tgt',
       u'fumbles', u'fumbles_recovered', u'fum_ret_yds', u'fum_tds',
       u'forced_fumbles', u'pro_bowls', u'all_pros', u'position', u'100yd_gms',
       u'yac', u'first_down_ctchs', u'first_down_ctchpct', u'long_ctch',
       u'recs_ovr_25', u'drops', u'EYds', u'DVOA', u'DYAR', u'position.1',
       u'Hand Size in', u'Arm Length in', u'40 Yard', u'Vert Leap in',
       u'Broad Jump in', u'Shuttle', u'3Cone', u'60Yd Shuttle',
       u'team_pass_tds', u'team_pass_yds', u'team_pass_attempts',
       u'team_completions', u'total_points', u'rookie_age', u'rookie_season',
       u'height_inches', u'start_ratio', u'dpis_drawn', u'dpi_yards',
       u'pct_team_tgts', u'pct_team_receptions', u'pct_of_team_passyards',
       u'pct_team_touchdowns', u'years_in_league', u'dropK', u'yacK', u'base',
       u'td_points', u'compilation'],
      dtype='object')

In [5]:
values = ['name','age', 'team', 'weight', 'games', 'targets', 'first_down_ctchs', 'receptions', 'yac', 'team']

In [6]:
# Define a function that splits a pivoted dataframe into its training and target set
cols = ['years_in_league', 'name', 'season', 'team']
df[cols].head(15)

    years_in_league            name  season team
0               0.0    David Boston  1999.0  ARI
1               0.0   Frank Sanders  1999.0  ARI
2               0.0       Rob Moore  1999.0  ARI
3               0.0        Mac Cody  1999.0  ARI
4               1.0   Frank Sanders  2000.0  ARI
5               1.0        Mac Cody  2000.0  ARI
6               0.0  Arnold Jackson  2001.0  ARI
7               2.0   Frank Sanders  2001.0  ARI
8               2.0  MarTay Jenkins  2001.0  ARI
9               0.0      Nate Poole  2002.0  ARI
10              3.0  MarTay Jenkins  2002.0  ARI
11              0.0  Jason McAddley  2002.0  ARI
12              3.0   Frank Sanders  2002.0  ARI
13              3.0    David Boston  2002.0  ARI
14              3.0   Bryan Gilmore  2003.0  ARI

In [7]:
# This will create a dataframe that has all the players who were rookies three seasons ago, and are therefore entering their fourth seasons.
x = df[((df.years_in_league == 0)&(df.season==2013))|((df.years_in_league==1)&(df.season==2014))|((df.years_in_league==2)&(df.season==2015))|((df.years_in_league==3)&(df.season==2016))]

In [8]:
cols = [ 'season', 'age', 'team', 'yac', 'receptions']
df2 = df[(df.years_in_league>=0)&(df.years_in_league<=3)]

In [9]:
print df2.shape

df2.head()

(2367, 69)

,name,season,age,draft_pos,team,weight,bmi,games,rush_atts,rush_yds,...,pct_team_tgts,pct_team_receptions,pct_of_team_passyards,pct_team_touchdowns,years_in_league,dropK,yacK,base,td_points,compilation
0,David Boston,1999.0,21.0,1-8,ARI,240.0,30.8,16.0,5.0,0.0,...,0.145161,0.139373,0.168748,0.181818,0.0,1.609438,31.985201,0.074346,0.159658,8.552186
1,Frank Sanders,1999.0,26.0,2-47,ARI,215.0,27.6,16.0,0.0,0.0,...,0.274194,0.275261,0.340350,0.090909,0.0,2.708050,70.315514,0.369168,0.039915,37.196235
2,Rob Moore,1999.0,31.0,1-1,ARI,203.0,25.4,14.0,0.0,0.0,...,0.172043,0.128920,0.221548,0.454545,0.0,1.386294,17.753623,0.128205,0.997865,19.805583
3,Mac Cody,1999.0,27.0,UDFA,ARI,182.0,25.4,13.0,0.0,0.0,...,0.019713,0.020906,0.021406,0.090909,0.0,0.000000,7.350000,0.002884,0.039915,0.567829
4,Frank Sanders,2000.0,27.0,2-47,ARI,215.0,27.6,16.0,0.0,0.0,...,0.209386,0.170886,0.230462,0.375000,1.0,2.484907,37.234980,0.235628,0.987886,30.478033

In [10]:
df3 = df[(df.rookie_season <2013)& (df.years_in_league<=3)]
df3.head()

,name,season,age,draft_pos,team,weight,bmi,games,rush_atts,rush_yds,...,pct_team_tgts,pct_team_receptions,pct_of_team_passyards,pct_team_touchdowns,years_in_league,dropK,yacK,base,td_points,compilation
0,David Boston,1999.0,21.0,1-8,ARI,240.0,30.8,16.0,5.0,0.0,...,0.145161,0.139373,0.168748,0.181818,0.0,1.609438,31.985201,0.074346,0.159658,8.552186
1,Frank Sanders,1999.0,26.0,2-47,ARI,215.0,27.6,16.0,0.0,0.0,...,0.274194,0.275261,0.340350,0.090909,0.0,2.708050,70.315514,0.369168,0.039915,37.196235
2,Rob Moore,1999.0,31.0,1-1,ARI,203.0,25.4,14.0,0.0,0.0,...,0.172043,0.128920,0.221548,0.454545,0.0,1.386294,17.753623,0.128205,0.997865,19.805583
3,Mac Cody,1999.0,27.0,UDFA,ARI,182.0,25.4,13.0,0.0,0.0,...,0.019713,0.020906,0.021406,0.090909,0.0,0.000000,7.350000,0.002884,0.039915,0.567829
4,Frank Sanders,2000.0,27.0,2-47,ARI,215.0,27.6,16.0,0.0,0.0,...,0.209386,0.170886,0.230462,0.375000,1.0,2.484907,37.234980,0.235628,0.987886,30.478033

In [11]:
pivoted = df3.pivot_table(index=df3.name, columns='years_in_league', values=cols)
pivoted.head()

                 season                           age                    \
years_in_league     0.0     1.0     2.0     3.0   0.0   1.0   2.0   3.0
name
A.J. Green       2011.0  2012.0  2013.0  2014.0  23.0  24.0  25.0  26.0
A.J. Jenkins     2012.0  2013.0     NaN     NaN  23.0  24.0   NaN   NaN
Aaron Brown      2009.0     NaN     NaN     NaN  24.0   NaN   NaN   NaN
Aaron Halterman  2007.0     NaN     NaN     NaN  25.0   NaN   NaN   NaN
Aaron Moorehead  2003.0  2004.0  2005.0  2006.0  23.0  24.0  25.0  26.0

                   yac                      receptions
years_in_league    0.0    1.0    2.0    3.0        0.0   1.0   2.0   3.0
name
A.J. Green       293.0  434.0  419.0  351.0       65.0  97.0  98.0  69.0
A.J. Jenkins       0.0   46.0    NaN    NaN        0.0   8.0   NaN   NaN
Aaron Brown       84.0    NaN    NaN    NaN        9.0   NaN   NaN   NaN
Aaron Halterman    3.0    NaN    NaN    NaN        1.0   NaN   NaN   NaN
Aaron Moorehead   16.0    3.0   18.0   12.0        7.0   1.0   7.0   8.0

In [12]:
mi = pivoted.columns
mi

MultiIndex(levels=[[u'season', u'age', u'yac', u'receptions'], [0.0, 1.0, 2.0, 3.0]],
           labels=[[0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3], [0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]],
           names=[None, u'years_in_league'])

In [13]:
mi.tolist()

[('season', 0.0),
 ('season', 1.0),
 ('season', 2.0),
 ('season', 3.0),
 ('age', 0.0),
 ('age', 1.0),
 ('age', 2.0),
 ('age', 3.0),
 ('yac', 0.0),
 ('yac', 1.0),
 ('yac', 2.0),
 ('yac', 3.0),
 ('receptions', 0.0),
 ('receptions', 1.0),
 ('receptions', 2.0),
 ('receptions', 3.0)]

In [14]:
new_cols = pd.Index([x[0]+'_'+str(x[1]) for x in mi.tolist()])
new_cols

Index([u'season_0.0', u'season_1.0', u'season_2.0', u'season_3.0', u'age_0.0',
       u'age_1.0', u'age_2.0', u'age_3.0', u'yac_0.0', u'yac_1.0', u'yac_2.0',
       u'yac_3.0', u'receptions_0.0', u'receptions_1.0', u'receptions_2.0',
       u'receptions_3.0'],
      dtype='object')

In [15]:
pivoted.columns = new_cols
print pivoted.columns
pivoted.head()

Index([u'season_0.0', u'season_1.0', u'season_2.0', u'season_3.0', u'age_0.0',
       u'age_1.0', u'age_2.0', u'age_3.0', u'yac_0.0', u'yac_1.0', u'yac_2.0',
       u'yac_3.0', u'receptions_0.0', u'receptions_1.0', u'receptions_2.0',
       u'receptions_3.0'],
      dtype='object')

,season_0.0,season_1.0,season_2.0,season_3.0,age_0.0,age_1.0,age_2.0,age_3.0,yac_0.0,yac_1.0,yac_2.0,yac_3.0,receptions_0.0,receptions_1.0,receptions_2.0,receptions_3.0
name,,,,,,,,,,,,,,,,
A.J. Green,2011.0,2012.0,2013.0,2014.0,23.0,24.0,25.0,26.0,293.0,434.0,419.0,351.0,65.0,97.0,98.0,69.0
A.J. Jenkins,2012.0,2013.0,NaN,NaN,23.0,24.0,NaN,NaN,0.0,46.0,NaN,NaN,0.0,8.0,NaN,NaN
Aaron Brown,2009.0,NaN,NaN,NaN,24.0,NaN,NaN,NaN,84.0,NaN,NaN,NaN,9.0,NaN,NaN,NaN
Aaron Halterman,2007.0,NaN,NaN,NaN,25.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN
Aaron Moorehead,2003.0,2004.0,2005.0,2006.0,23.0,24.0,25.0,26.0,16.0,3.0,18.0,12.0,7.0,1.0,7.0,8.0

In [16]:
pivoted.rename(columns = lambda x: x.replace('.0', ''), inplace = True)
pivoted.head()

,season_0,season_1,season_2,season_3,age_0,age_1,age_2,age_3,yac_0,yac_1,yac_2,yac_3,receptions_0,receptions_1,receptions_2,receptions_3
name,,,,,,,,,,,,,,,,
A.J. Green,2011.0,2012.0,2013.0,2014.0,23.0,24.0,25.0,26.0,293.0,434.0,419.0,351.0,65.0,97.0,98.0,69.0
A.J. Jenkins,2012.0,2013.0,NaN,NaN,23.0,24.0,NaN,NaN,0.0,46.0,NaN,NaN,0.0,8.0,NaN,NaN
Aaron Brown,2009.0,NaN,NaN,NaN,24.0,NaN,NaN,NaN,84.0,NaN,NaN,NaN,9.0,NaN,NaN,NaN
Aaron Halterman,2007.0,NaN,NaN,NaN,25.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN
Aaron Moorehead,2003.0,2004.0,2005.0,2006.0,23.0,24.0,25.0,26.0,16.0,3.0,18.0,12.0,7.0,1.0,7.0,8.0

In [17]:
new_df = df[(df.rookie_season <2013)& (df.years_in_league<=3)]
new_df.head()

,name,season,age,draft_pos,team,weight,bmi,games,rush_atts,rush_yds,...,pct_team_tgts,pct_team_receptions,pct_of_team_passyards,pct_team_touchdowns,years_in_league,dropK,yacK,base,td_points,compilation
0,David Boston,1999.0,21.0,1-8,ARI,240.0,30.8,16.0,5.0,0.0,...,0.145161,0.139373,0.168748,0.181818,0.0,1.609438,31.985201,0.074346,0.159658,8.552186
1,Frank Sanders,1999.0,26.0,2-47,ARI,215.0,27.6,16.0,0.0,0.0,...,0.274194,0.275261,0.340350,0.090909,0.0,2.708050,70.315514,0.369168,0.039915,37.196235
2,Rob Moore,1999.0,31.0,1-1,ARI,203.0,25.4,14.0,0.0,0.0,...,0.172043,0.128920,0.221548,0.454545,0.0,1.386294,17.753623,0.128205,0.997865,19.805583
3,Mac Cody,1999.0,27.0,UDFA,ARI,182.0,25.4,13.0,0.0,0.0,...,0.019713,0.020906,0.021406,0.090909,0.0,0.000000,7.350000,0.002884,0.039915,0.567829
4,Frank Sanders,2000.0,27.0,2-47,ARI,215.0,27.6,16.0,0.0,0.0,...,0.209386,0.170886,0.230462,0.375000,1.0,2.484907,37.234980,0.235628,0.987886,30.478033

In [18]:
cols_df = new_df.drop('name', axis = 1)
cols_df = cols_df.drop('years_in_league', axis = 1)

In [19]:
piv_df = new_df.pivot_table(index=new_df.name, columns='years_in_league', values=cols_df.columns)
piv_df.head()

                 season                           age                    \
years_in_league     0.0     1.0     2.0     3.0   0.0   1.0   2.0   3.0
name
A.J. Green       2011.0  2012.0  2013.0  2014.0  23.0  24.0  25.0  26.0
A.J. Jenkins     2012.0  2013.0     NaN     NaN  23.0  24.0   NaN   NaN
Aaron Brown      2009.0     NaN     NaN     NaN  24.0   NaN   NaN   NaN
Aaron Halterman  2007.0     NaN     NaN     NaN  25.0   NaN   NaN   NaN
Aaron Moorehead  2003.0  2004.0  2005.0  2006.0  23.0  24.0  25.0  26.0

                weight           ...          base           td_points  \
years_in_league    0.0    1.0    ...           2.0       3.0       0.0
name                             ...
A.J. Green       205.0  205.0    ...      0.719977  0.542096  1.024475
A.J. Jenkins     192.0  192.0    ...           NaN       NaN  0.000000
Aaron Brown      196.0    NaN    ...           NaN       NaN  0.027441
Aaron Halterman  255.0    NaN    ...           NaN       NaN  0.000000
Aaron Moorehead  200.0  200.0    ...      0.002225  0.001842  0.000000

                                              compilation             \
years_in_league       1.0       2.0       3.0         0.0        1.0
name
A.J. Green       1.897369  1.562539  0.790309   53.006410  98.471570
A.J. Jenkins     0.000000       NaN       NaN         NaN   0.597268
Aaron Brown           NaN       NaN       NaN    1.007213        NaN
Aaron Halterman       NaN       NaN       NaN    0.030196        NaN
Aaron Moorehead  0.000000  0.000000  0.012914    0.240777   0.025880


years_in_league        2.0        3.0
name
A.J. Green       82.935491  59.741763
A.J. Jenkins           NaN        NaN
Aaron Brown            NaN        NaN
Aaron Halterman        NaN        NaN
Aaron Moorehead   0.222518   0.274562

[5 rows x 252 columns]

In [20]:
mi = piv_df.columns
mi

MultiIndex(levels=[[u'season', u'age', u'weight', u'bmi', u'games', u'rush_atts', u'rush_yds', u'rush_y/a', u'rush_tds', u'rush_ypg', u'targets', u'receptions', u'rec_yards', u'yards/reception', u'rec_tds', u'rec_ypg', u'ctch_pct', u'y/tgt', u'fumbles', u'fumbles_recovered', u'fum_ret_yds', u'fum_tds', u'forced_fumbles', u'pro_bowls', u'all_pros', u'100yd_gms', u'yac', u'first_down_ctchs', u'first_down_ctchpct', u'long_ctch', u'recs_ovr_25', u'drops', u'EYds', u'DVOA', u'DYAR', u'Hand Size in', u'Arm Length in', u'40 Yard', u'Vert Leap in', u'Broad Jump in', u'Shuttle', u'3Cone', u'60Yd Shuttle', u'team_pass_tds', u'team_pass_yds', u'team_pass_attempts', u'team_completions', u'total_points', u'rookie_age', u'rookie_season', u'height_inches', u'start_ratio', u'dpis_drawn', u'dpi_yards', u'pct_team_tgts', u'pct_team_receptions', u'pct_of_team_passyards', u'pct_team_touchdowns', u'dropK', u'yacK', u'base', u'td_points', u'compilation'], [0.0, 1.0, 2.0, 3.0]],
           labels=[[0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 9, 9, 9, 9, 10, 10, 10, 10, 11, 11, 11, 11, 12, 12, 12, 12, 13, 13, 13, 13, 14, 14, 14, 14, 15, 15, 15, 15, 16, 16, 16, 16, 17, 17, 17, 17, 18, 18, 18, 18, 19, 19, 19, 19, 20, 20, 20, 20, 21, 21, 21, 21, 22, 22, 22, 22, 23, 23, 23, 23, 24, 24, 24, 24, 25, 25, 25, 25, 26, 26, 26, 26, 27, 27, 27, 27, 28, 28, 28, 28, 29, 29, 29, 29, 30, 30, 30, 30, 31, 31, 31, 31, 32, 32, 32, 32, 33, 33, 33, 33, 34, 34, 34, 34, 35, 35, 35, 35, 36, 36, 36, 36, 37, 37, 37, 37, 38, 38, 38, 38, 39, 39, 39, 39, 40, 40, 40, 40, 41, 41, 41, 41, 42, 42, 42, 42, 43, 43, 43, 43, 44, 44, 44, 44, 45, 45, 45, 45, 46, 46, 46, 46, 47, 47, 47, 47, 48, 48, 48, 48, 49, 49, 49, 49, 50, 50, 50, 50, 51, 51, 51, 51, 52, 52, 52, 52, 53, 53, 53, 53, 54, 54, 54, 54, 55, 55, 55, 55, 56, 56, 56, 56, 57, 57, 57, 57, 58, 58, 58, 58, 59, 59, 59, 59, 60, 60, 60, 60, 61, 61, 61, 61, 62, 62, 62, 62], [0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]],
           names=[None, u'years_in_league'])

In [21]:
new_cols = pd.Index([x[0]+'_'+str(x[1]) for x in mi.tolist()])
new_cols

Index([u'season_0.0', u'season_1.0', u'season_2.0', u'season_3.0', u'age_0.0',
       u'age_1.0', u'age_2.0', u'age_3.0', u'weight_0.0', u'weight_1.0',
       ...
       u'base_2.0', u'base_3.0', u'td_points_0.0', u'td_points_1.0',
       u'td_points_2.0', u'td_points_3.0', u'compilation_0.0',
       u'compilation_1.0', u'compilation_2.0', u'compilation_3.0'],
      dtype='object', length=252)

In [22]:
piv_df.columns = new_cols
print piv_df.columns
piv_df.head()

Index([u'season_0.0', u'season_1.0', u'season_2.0', u'season_3.0', u'age_0.0',
       u'age_1.0', u'age_2.0', u'age_3.0', u'weight_0.0', u'weight_1.0',
       ...
       u'base_2.0', u'base_3.0', u'td_points_0.0', u'td_points_1.0',
       u'td_points_2.0', u'td_points_3.0', u'compilation_0.0',
       u'compilation_1.0', u'compilation_2.0', u'compilation_3.0'],
      dtype='object', length=252)

,season_0.0,season_1.0,season_2.0,season_3.0,age_0.0,age_1.0,age_2.0,age_3.0,weight_0.0,weight_1.0,...,base_2.0,base_3.0,td_points_0.0,td_points_1.0,td_points_2.0,td_points_3.0,compilation_0.0,compilation_1.0,compilation_2.0,compilation_3.0
name,,,,,,,,,,,,,,,,,,,,,
A.J. Green,2011.0,2012.0,2013.0,2014.0,23.0,24.0,25.0,26.0,205.0,205.0,...,0.719977,0.542096,1.024475,1.897369,1.562539,0.790309,53.006410,98.471570,82.935491,59.741763
A.J. Jenkins,2012.0,2013.0,NaN,NaN,23.0,24.0,NaN,NaN,192.0,192.0,...,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN,0.597268,NaN,NaN
Aaron Brown,2009.0,NaN,NaN,NaN,24.0,NaN,NaN,NaN,196.0,NaN,...,NaN,NaN,0.027441,NaN,NaN,NaN,1.007213,NaN,NaN,NaN
Aaron Halterman,2007.0,NaN,NaN,NaN,25.0,NaN,NaN,NaN,255.0,NaN,...,NaN,NaN,0.000000,NaN,NaN,NaN,0.030196,NaN,NaN,NaN
Aaron Moorehead,2003.0,2004.0,2005.0,2006.0,23.0,24.0,25.0,26.0,200.0,200.0,...,0.002225,0.001842,0.000000,0.000000,0.000000,0.012914,0.240777,0.025880,0.222518,0.274562

In [23]:
cols_to_keep = []
for col in piv_df.columns:
    print col+':'
    print piv_df[col].isnull().sum()
    print '===================='
    if piv_df[col].isnull().sum() == 0:
        cols_to_keep.append(col)

season_0.0:
26
====================
season_1.0:
390
====================
season_2.0:
491
====================
season_3.0:
574
====================
age_0.0:
26
====================
age_1.0:
390
====================
age_2.0:
491
====================
age_3.0:
574
====================
weight_0.0:
26
====================
weight_1.0:
390
====================
weight_2.0:
491
====================
weight_3.0:
574
====================
bmi_0.0:
26
====================
bmi_1.0:
390
====================
bmi_2.0:
491
====================
bmi_3.0:
574
====================
games_0.0:
26
====================
games_1.0:
390
====================
games_2.0:
491
====================
games_3.0:
574
====================
rush_atts_0.0:
26
====================
rush_atts_1.0:
390
====================
rush_atts_2.0:
491
====================
rush_atts_3.0:
574
====================
rush_yds_0.0:
26
====================
rush_yds_1.0:
390
====================
rush_yds_2.0:
491
====================
rush_yds_3.0:
574
====================
rush_y/a_0.0:
26
====================
rush_y/a_1.0:
390
====================
rush_y/a_2.0:
491
====================
rush_y/a_3.0:
574
====================
rush_tds_0.0:
26
====================
rush_tds_1.0:
390
====================
rush_tds_2.0:
491
====================
rush_tds_3.0:
574
====================
rush_ypg_0.0:
26
====================
rush_ypg_1.0:
390
====================
rush_ypg_2.0:
491
====================
rush_ypg_3.0:
574
====================
targets_0.0:
26
====================
targets_1.0:
390
====================
targets_2.0:
491
====================
targets_3.0:
574
====================
receptions_0.0:
26
====================
receptions_1.0:
390
====================
receptions_2.0:
491
====================
receptions_3.0:
574
====================
rec_yards_0.0:
26
====================
rec_yards_1.0:
390
====================
rec_yards_2.0:
491
====================
rec_yards_3.0:
574
====================
yards/reception_0.0:
26
====================
yards/reception_1.0:
390
====================
yards/reception_2.0:
491
====================
yards/reception_3.0:
574
====================
rec_tds_0.0:
26
====================
rec_tds_1.0:
390
====================
rec_tds_2.0:
491
====================
rec_tds_3.0:
574
====================
rec_ypg_0.0:
26
====================
rec_ypg_1.0:
390
====================
rec_ypg_2.0:
491
====================
rec_ypg_3.0:
574
====================
ctch_pct_0.0:
26
====================
ctch_pct_1.0:
390
====================
ctch_pct_2.0:
491
====================
ctch_pct_3.0:
574
====================
y/tgt_0.0:
26
====================
y/tgt_1.0:
390
====================
y/tgt_2.0:
491
====================
y/tgt_3.0:
574
====================
fumbles_0.0:
26
====================
fumbles_1.0:
390
====================
fumbles_2.0:
491
====================
fumbles_3.0:
574
====================
fumbles_recovered_0.0:
26
====================
fumbles_recovered_1.0:
390
====================
fumbles_recovered_2.0:
491
====================
fumbles_recovered_3.0:
574
====================
fum_ret_yds_0.0:
26
====================
fum_ret_yds_1.0:
390
====================
fum_ret_yds_2.0:
491
====================
fum_ret_yds_3.0:
574
====================
fum_tds_0.0:
26
====================
fum_tds_1.0:
390
====================
fum_tds_2.0:
491
====================
fum_tds_3.0:
574
====================
forced_fumbles_0.0:
26
====================
forced_fumbles_1.0:
390
====================
forced_fumbles_2.0:
491
====================
forced_fumbles_3.0:
574
====================
pro_bowls_0.0:
26
====================
pro_bowls_1.0:
390
====================
pro_bowls_2.0:
491
====================
pro_bowls_3.0:
574
====================
all_pros_0.0:
26
====================
all_pros_1.0:
390
====================
all_pros_2.0:
491
====================
all_pros_3.0:
574
====================
100yd_gms_0.0:
26
====================
100yd_gms_1.0:
390
====================
100yd_gms_2.0:
491
====================
100yd_gms_3.0:
574
====================
yac_0.0:
178
====================
yac_1.0:
443
====================
yac_2.0:
540
====================
yac_3.0:
600
====================
first_down_ctchs_0.0:
26
====================
first_down_ctchs_1.0:
390
====================
first_down_ctchs_2.0:
491
====================
first_down_ctchs_3.0:
574
====================
first_down_ctchpct_0.0:
26
====================
first_down_ctchpct_1.0:
390
====================
first_down_ctchpct_2.0:
491
====================
first_down_ctchpct_3.0:
574
====================
long_ctch_0.0:
26
====================
long_ctch_1.0:
390
====================
long_ctch_2.0:
491
====================
long_ctch_3.0:
574
====================
recs_ovr_25_0.0:
178
====================
recs_ovr_25_1.0:
443
====================
recs_ovr_25_2.0:
540
====================
recs_ovr_25_3.0:
600
====================
drops_0.0:
26
====================
drops_1.0:
390
====================
drops_2.0:
491
====================
drops_3.0:
574
====================
EYds_0.0:
26
====================
EYds_1.0:
390
====================
EYds_2.0:
491
====================
EYds_3.0:
574
====================
DVOA_0.0:
26
====================
DVOA_1.0:
390
====================
DVOA_2.0:
491
====================
DVOA_3.0:
574
====================
DYAR_0.0:
26
====================
DYAR_1.0:
390
====================
DYAR_2.0:
491
====================
DYAR_3.0:
574
====================
Hand Size in_0.0:
858
====================
Hand Size in_1.0:
858
====================
Hand Size in_2.0:
867
====================
Hand Size in_3.0:
868
====================
Arm Length in_0.0:
858
====================
Arm Length in_1.0:
858
====================
Arm Length in_2.0:
867
====================
Arm Length in_3.0:
868
====================
40 Yard_0.0:
26
====================
40 Yard_1.0:
390
====================
40 Yard_2.0:
491
====================
40 Yard_3.0:
574
====================
Vert Leap in_0.0:
753
====================
Vert Leap in_1.0:
762
====================
Vert Leap in_2.0:
780
====================
Vert Leap in_3.0:
792
====================
Broad Jump in_0.0:
764
====================
Broad Jump in_1.0:
769
====================
Broad Jump in_2.0:
787
====================
Broad Jump in_3.0:
795
====================
Shuttle_0.0:
783
====================
Shuttle_1.0:
785
====================
Shuttle_2.0:
804
====================
Shuttle_3.0:
809
====================
3Cone_0.0:
786
====================
3Cone_1.0:
787
====================
3Cone_2.0:
806
====================
3Cone_3.0:
811
====================
60Yd Shuttle_0.0:
873
====================
60Yd Shuttle_1.0:
876
====================
60Yd Shuttle_2.0:
880
====================
60Yd Shuttle_3.0:
879
====================
team_pass_tds_0.0:
26
====================
team_pass_tds_1.0:
390
====================
team_pass_tds_2.0:
491
====================
team_pass_tds_3.0:
574
====================
team_pass_yds_0.0:
26
====================
team_pass_yds_1.0:
390
====================
team_pass_yds_2.0:
491
====================
team_pass_yds_3.0:
574
====================
team_pass_attempts_0.0:
26
====================
team_pass_attempts_1.0:
390
====================
team_pass_attempts_2.0:
491
====================
team_pass_attempts_3.0:
574
====================
team_completions_0.0:
26
====================
team_completions_1.0:
390
====================
team_completions_2.0:
491
====================
team_completions_3.0:
574
====================
total_points_0.0:
26
====================
total_points_1.0:
390
====================
total_points_2.0:
491
====================
total_points_3.0:
574
====================
rookie_age_0.0:
26
====================
rookie_age_1.0:
390
====================
rookie_age_2.0:
491
====================
rookie_age_3.0:
574
====================
rookie_season_0.0:
26
====================
rookie_season_1.0:
390
====================
rookie_season_2.0:
491
====================
rookie_season_3.0:
574
====================
height_inches_0.0:
26
====================
height_inches_1.0:
390
====================
height_inches_2.0:
491
====================
height_inches_3.0:
574
====================
start_ratio_0.0:
26
====================
start_ratio_1.0:
390
====================
start_ratio_2.0:
491
====================
start_ratio_3.0:
574
====================
dpis_drawn_0.0:
26
====================
dpis_drawn_1.0:
390
====================
dpis_drawn_2.0:
491
====================
dpis_drawn_3.0:
574
====================
dpi_yards_0.0:
26
====================
dpi_yards_1.0:
390
====================
dpi_yards_2.0:
491
====================
dpi_yards_3.0:
574
====================
pct_team_tgts_0.0:
26
====================
pct_team_tgts_1.0:
390
====================
pct_team_tgts_2.0:
491
====================
pct_team_tgts_3.0:
574
====================
pct_team_receptions_0.0:
26
====================
pct_team_receptions_1.0:
390
====================
pct_team_receptions_2.0:
491
====================
pct_team_receptions_3.0:
574
====================
pct_of_team_passyards_0.0:
26
====================
pct_of_team_passyards_1.0:
390
====================
pct_of_team_passyards_2.0:
491
====================
pct_of_team_passyards_3.0:
574
====================
pct_team_touchdowns_0.0:
26
====================
pct_team_touchdowns_1.0:
390
====================
pct_team_touchdowns_2.0:
491
====================
pct_team_touchdowns_3.0:
574
====================
dropK_0.0:
26
====================
dropK_1.0:
390
====================
dropK_2.0:
491
====================
dropK_3.0:
574
====================
yacK_0.0:
26
====================
yacK_1.0:
390
====================
yacK_2.0:
491
====================
yacK_3.0:
574
====================
base_0.0:
243
====================
base_1.0:
463
====================
base_2.0:
549
====================
base_3.0:
605
====================
td_points_0.0:
26
====================
td_points_1.0:
390
====================
td_points_2.0:
491
====================
td_points_3.0:
574
====================
compilation_0.0:
243
====================
compilation_1.0:
463
====================
compilation_2.0:
549
====================
compilation_3.0:
605
====================

In [24]:
piv_df = piv_df[cols_to_keep]
piv_df

Empty DataFrame
Columns: []
Index: [A.J. Green, A.J. Jenkins, Aaron Brown, Aaron Halterman, Aaron Moorehead, Aaron Walker, Adam Jennings, Adrian Arrington, Adrian Madise, Ahmad Merritt, Ahmard Hall, Airese Currie, Albert Connell, Albert Johnson, Aldrick Robinson, Alex Bannister, Alex Smith, Alex Van Dyke, Alge Crumpler, Allen Rossum, Alonzo Mayes, Alshon Jeffery, Alvin Harper, Alvis Whitted, Amani Toomer, Andra Davis, Andrae Thurman, Andre Caldwell, Andre Cooper, Andre Hastings, Andre Holmes, Andre Johnson, Andre King, Andre Rison, Andre Roberts, Andre' Davis, Andrew Glover, Andrew Hawkins, Andy McCullough, Anquan Boldin, Anthony Armstrong, Anthony Becht, Anthony Bright, Anthony Fasano, Anthony Gonzalez, Antonio Brown, Antonio Bryant, Antonio Chatman, Antonio Freeman, Antwaan Randle El, Anwar Phillips, Arland Bruce, Armanti Edwards, Arnaz Battle, Arnold Jackson, Arrelious Benn, Ashley Lelie, Atnaf Harris, Aundrae Allison, Austin Collie, Austin Pettis, Avion Black, Az-Zahir Hakim, B.J. Cunningham, B.J. Sams, Bam Childress, Ben Hartsock, Ben Nelson, Ben Obomanu, Ben Patrick, Bernard Berrian, Bert Emanuel, Bethel Johnson, Bill Schroeder, Billy Bajema, Billy Davis, Billy McMullen, Billy Miller, Biren Ealy, Blair White, Bobby Brown, Bobby Collins, Bobby Engram, Bobby Shaw, Bobby Sippio, Bobby Wade, Brad Pyatt, Brad Smith, Brandon Banks, Brandon Gibson, Brandon James, Brandon Jones, Brandon LaFell, Brandon Lloyd, Brandon London, Brandon Manumaleuna, Brandon Marshall, Brandon Middleton, Brandon Rideau, Brandon Stokley, ...]

[898 rows x 0 columns]

In [25]:
piv_df.dropna(axis = 0, inplace = True)
piv_df

Empty DataFrame
Columns: []
Index: [A.J. Green, A.J. Jenkins, Aaron Brown, Aaron Halterman, Aaron Moorehead, Aaron Walker, Adam Jennings, Adrian Arrington, Adrian Madise, Ahmad Merritt, Ahmard Hall, Airese Currie, Albert Connell, Albert Johnson, Aldrick Robinson, Alex Bannister, Alex Smith, Alex Van Dyke, Alge Crumpler, Allen Rossum, Alonzo Mayes, Alshon Jeffery, Alvin Harper, Alvis Whitted, Amani Toomer, Andra Davis, Andrae Thurman, Andre Caldwell, Andre Cooper, Andre Hastings, Andre Holmes, Andre Johnson, Andre King, Andre Rison, Andre Roberts, Andre' Davis, Andrew Glover, Andrew Hawkins, Andy McCullough, Anquan Boldin, Anthony Armstrong, Anthony Becht, Anthony Bright, Anthony Fasano, Anthony Gonzalez, Antonio Brown, Antonio Bryant, Antonio Chatman, Antonio Freeman, Antwaan Randle El, Anwar Phillips, Arland Bruce, Armanti Edwards, Arnaz Battle, Arnold Jackson, Arrelious Benn, Ashley Lelie, Atnaf Harris, Aundrae Allison, Austin Collie, Austin Pettis, Avion Black, Az-Zahir Hakim, B.J. Cunningham, B.J. Sams, Bam Childress, Ben Hartsock, Ben Nelson, Ben Obomanu, Ben Patrick, Bernard Berrian, Bert Emanuel, Bethel Johnson, Bill Schroeder, Billy Bajema, Billy Davis, Billy McMullen, Billy Miller, Biren Ealy, Blair White, Bobby Brown, Bobby Collins, Bobby Engram, Bobby Shaw, Bobby Sippio, Bobby Wade, Brad Pyatt, Brad Smith, Brandon Banks, Brandon Gibson, Brandon James, Brandon Jones, Brandon LaFell, Brandon Lloyd, Brandon London, Brandon Manumaleuna, Brandon Marshall, Brandon Middleton, Brandon Rideau, Brandon Stokley, ...]

[898 rows x 0 columns]

In [26]:
X = piv_df[cols_to_keep]
y = piv_df['compilation_3.0']

KeyError: 'compilation_3.0'

In [ ]:
from sklearn.cross_validation import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

In [ ]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

model = lr.fit(X_train, y_train)

model.score(X_test, y_test)