```SELECT combine_stats."Name", combine_stats."College", combine_stats."POS", combine_stats."40 Yard", combine_stats."Year"
FROM combine_stats
WHERE combine_stats."40 Yard" >= '1'
ORDER BY combine_stats."40 Yard" asc
LIMIT 25;

SELECT fox_defense."ints", fox_defense."name", 
        fox_defense."season", fox_defense."team", fox_defense."sacks"
FROM fox_defense
ORDER BY fox_defense."sacks" DESC;

SELECT *
FROM fox_defense
WHERE fox_defense."team" = 'III';


These next three commands do replace places where team values are null with '2TM' which is how pro-football-reference and football outsiders indicate a player who played for two teams in a season;

UPDATE fox_receiving 
SET "team" = '2TM' 
WHERE "team" is null;

UPDATE fox_passing
SET "team" = '2TM' 
WHERE "team" is null;

UPDATE fox_rushing 
SET "team" = '2TM' 
WHERE "team" is null;


SELECT fox_receiving."yac", wide_receivers.*
FROM fox_receiving
JOIN wide_receivers 
ON fox_receiving."name"  LIKE '%' || wide_receivers."name" || '%'
AND fox_receiving."season" = wide_receivers."season";

SELECT * 
FROM fo_tes;

DROP TABLE fo_rbs;

SELECT *
FROM fo_rbs;

SELECT wide_receivers.*, fox_receiving."100yd_gms", fox_receiving."yac", fox_receiving."first_down_ctchs", fox_receiving."first_down_ctchpct", fox_receiving."long_ctch", fox_receiving."recs_ovr_25", fox_receiving."drops", fo_wrs."EYds", fo_wrs."DPI", fo_wrs."DVOA", fo_wrs."DYAR", fo_wrs."position", combine_stats."Hand Size in", combine_stats."Arm Length in", combine_stats."40 Yard", combine_stats."Vert Leap in", combine_stats."Broad Jump in", combine_stats."Shuttle", combine_stats."3Cone", combine_stats."60Yd Shuttle"
FROM wide_receivers
JOIN fox_receiving 
ON CONCAT(wide_receivers."name", wide_receivers."team") = CONCAT(fox_receiving."name", fox_receiving."team")
AND wide_receivers."season" = fox_receiving."season"
JOIN fo_wrs
ON CONCAT(lower(wide_receivers."name"), wide_receivers."team") = CONCAT(lower(fo_wrs."name"), fo_wrs."Team")
and wide_receivers."season" = fo_wrs."season"
left JOIN combine_stats
ON wide_receivers."name" = combine_stats."Name"
AND LOWER(fo_wrs."position") = LOWER(combine_stats."POS");

SELECT DISTINCT("team")
FROM wide_receivers;

UPDATE wide_receivers
SET "team" = 'SF'
WHERE "team" = 'SFO';

UPDATE wide_receivers
SET "team" = 'GB'
WHERE "team" = 'GNB';

UPDATE wide_receivers
SET "team" = 'NE'
WHERE "team" = 'NWE';

UPDATE wide_receivers
SET "team" = 'TB'
WHERE "team" = 'TAM';

UPDATE wide_receivers
SET "team" = 'NO'
WHERE "team" = 'NOR';

UPDATE wide_receivers
SET "team" = '2TM'
WHERE "team" = '3TM'
OR "team" = '4TM';

UPDATE wide_receivers
SET "team" = 'SD'
WHERE "team" = 'SDG';

SELECT wide_receivers.*, fox_receiving."100yd_gms", fox_receiving."yac", fox_receiving."first_down_ctchs", fox_receiving."first_down_ctchpct", fox_receiving."long_ctch", fox_receiving."recs_ovr_25", fox_receiving."drops", fo_wrs."EYds", fo_wrs."DPI", fo_wrs."DVOA", fo_wrs."DYAR", fo_wrs."position", combine_stats."Hand Size in", combine_stats."Arm Length in", combine_stats."40 Yard", combine_stats."Vert Leap in", combine_stats."Broad Jump in", combine_stats."Shuttle", combine_stats."3Cone", combine_stats."60Yd Shuttle"
FROM wide_receivers
LEFT JOIN fox_receiving 
ON CONCAT(wide_receivers."name", wide_receivers."team") = CONCAT(fox_receiving."name", fox_receiving."team")
AND wide_receivers."season" = fox_receiving."season"
LEFT JOIN fo_wrs
ON CONCAT(lower(wide_receivers."name"), wide_receivers."team") = CONCAT(lower(fo_wrs."name"), fo_wrs."Team")
and wide_receivers."season" = fo_wrs."season"
left JOIN combine_stats
ON wide_receivers."name" = combine_stats."Name"
AND LOWER(fo_wrs."position") = LOWER(combine_stats."POS")
WHERE wide_receivers."position" = 'wr';

SELECT *
FROM wide_receivers;

ALTER TABLE wide_receivers ADD COLUMN position character varying(50) DEFAULT 'wr';

UPDATE team_data
SET "team" = 'SF'
WHERE "team" = 'SFO';

UPDATE team_data
SET "team" = 'GB'
WHERE "team" = 'GNB';

UPDATE team_data
SET "team" = 'NE'
WHERE "team" = 'NWE';

UPDATE team_data
SET "team" = 'TB'
WHERE "team" = 'TAM';

UPDATE team_data
SET "team" = 'NO'
WHERE "team" = 'NOR';


SELECT wide_receivers.*, team_data."pf"
FROM wide_receivers
JOIN team_data
ON CONCAT(wide_receivers."team", wide_receivers."season") = CONCAT(team_data."team", team_data."year");


SELECT team_data."team", team_data."year", SUM(team_data."pf") as total_points, SUM(team_data.off_plys) as total_plays, SUM(team_data."tot_yds") as total_yards
FROM team_data
GROUP BY team_data."team", team_data."year";



CREATE TABLE team_offense
AS SELECT team_data."opp" as team,team_data."year" as season, sum(team_data."opp_pass_yds") as pass_yards, sum(team_data."opp_pass_tds") as pass_tds, sum(team_data."pa") as points_for, sum(team_data."def_plys") as total_plays, sum(team_data."opp_rush_yds") as rush_yards, sum(team_data."opp_pass_att") as pass_attempts, sum(team_data."opp_completions") as completions, sum(team_data."opp_rush_atts") as rush_attempts, sum(team_data."opp_rush_td") as rush_tds
FROM team_data
GROUP BY team_data."opp", team_data."year";

SELECT wide_receivers.*, fox_receiving."100yd_gms", fox_receiving."yac", fox_receiving."first_down_ctchs", fox_receiving."first_down_ctchpct", fox_receiving."long_ctch", fox_receiving."recs_ovr_25", fox_receiving."drops", fo_wrs."EYds", fo_wrs."DPI", fo_wrs."DVOA", fo_wrs."DYAR", fo_wrs."position", combine_stats."Hand Size in", combine_stats."Arm Length in", combine_stats."40 Yard", combine_stats."Vert Leap in", combine_stats."Broad Jump in", combine_stats."Shuttle", combine_stats."3Cone", combine_stats."60Yd Shuttle", team_offense."pass_tds" as team_pass_tds, team_offense."pass_yards" as team_pass_yds, team_offense."pass_attempts" as team_pass_attempts, team_offense."completions" as team_completions
FROM wide_receivers
LEFT JOIN fox_receiving 
ON CONCAT(wide_receivers."name", wide_receivers."team") = CONCAT(fox_receiving."name", fox_receiving."team")
AND wide_receivers."season" = fox_receiving."season"
LEFT JOIN fo_wrs
ON CONCAT(lower(wide_receivers."name"), wide_receivers."team") = CONCAT(lower(fo_wrs."name"), fo_wrs."Team")
and wide_receivers."season" = fo_wrs."season"
left JOIN combine_stats
ON wide_receivers."name" = combine_stats."Name"
AND LOWER(fo_wrs."position") = LOWER(combine_stats."POS")
LEFT JOIN team_offense
ON CONCAT(wide_receivers."team", wide_receivers."season") = CONCAT(team_offense."team", team_offense."season");

UPDATE team_offense
SET "team" = 'SF'
WHERE "team" = 'SFO';

UPDATE team_offense
SET "team" = 'GB'
WHERE "team" = 'GNB';

UPDATE team_offense
SET "team" = 'NE'
WHERE "team" = 'NWE';

UPDATE team_offense
SET "team" = 'TB'
WHERE "team" = 'TAM';

UPDATE team_offense
SET "team" = 'NO'
WHERE "team" = 'NOR';

SELECT wide_receivers."name", MIN(wide_receivers."season") as rookie_season, MIN(wide_receivers."age") as rookie_age
FROM wide_receivers
GROUP BY wide_receivers."name";

SELECT COUNT(DISTINCT(wide_receivers."name"))
from wide_receivers;

SELECT * FROM wide_receivers
WHERE "name" = 'Jerry Rice*';```